services:
  image-classifier:
    image: ghcr.io/prathmeshj1729/dp:1.1
    volumes:
      - /tmp/DPinput/inputdata:/app/data
      - /tmp/DPinput/config:/app/config
      - /tmp/DPoutput:/app/pipelineOutput